# Makefile for unit testing of all microservices

#Running the test code file that contains multiple tests for the microservices
test:
	python input_validation_test.py
	python addition_service_test.py
	python message_service_test.py
	python timestamp_service_test.py
	python random_number_test.py
	python return_service_test.py