apiVersion: apps/v1
kind: Deployment
metadata:
  name: timestamp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timestamp-service
  template:
    metadata:
      labels:
        app: timestamp-service
    spec:
      containers:
        - name: timestamp-service
          image: timestamp-service
          ports:
            - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: timestamp-service
spec:
  selector:
    app: timestamp-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003
  type: NodePort
